#!/usr/bin/perl -w

use strict;
use Delta;

(my $release = q$Revision$) =~ s/^[^:]+:\s*(.*?)\s*$/$1/;
(my $date = q$Date$) =~ s/^[^:]+:\s*(.*?)\s*$/$1/;        

my $delta = new Delta;

if (@ARGV != 2) {
	print "Half-Life delta converter: delta.lst -> xml\n";
	print "delta2xml (c) Uwe Girlich, Release $release, $date\n";
	printf "using Delta.pm, Release %s, %s\n", $delta->release(),
			$delta->date();
	print "delta2xml delta.lst delta.xml\n";
	exit;
}

my ($deltafilename, $xmlfilename) = @ARGV;

$delta->readfile_lst($deltafilename);
$delta->writefile_xml($xmlfilename);


